# Generated by Django 2.2.12 on 2020-06-24 17:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Colaborador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreColaborador', models.CharField(max_length=40)),
                ('link', models.URLField(max_length=500, null=True)),
                ('logo', models.ImageField(null=True, upload_to='Colaborador/')),
                ('fecha', models.DateField(null=True)),
            ],
            options={
                'verbose_name': 'Colaborador',
                'verbose_name_plural': 'Colaboradores',
            },
        ),
        migrations.CreateModel(
            name='Entidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreEntidad', models.CharField(max_length=40)),
                ('link', models.URLField(max_length=500, null=True)),
                ('logo', models.ImageField(null=True, upload_to='Entidades/')),
            ],
            options={
                'verbose_name': 'Entidad',
                'verbose_name_plural': 'Entidades',
            },
        ),
        migrations.CreateModel(
            name='Nosotros',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('image', models.FileField(blank=True, upload_to='')),
            ],
            options={
                'verbose_name': 'Imagen',
                'verbose_name_plural': 'Imagenes',
            },
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(blank=True, null=True)),
                ('nombreProyecto', models.CharField(max_length=40, null=True)),
                ('año', models.DateTimeField(verbose_name='fecha')),
                ('descripcion', models.CharField(max_length=300, null=True)),
                ('imagenes', models.FileField(upload_to='proyecto/')),
                ('video', models.FileField(null=True, upload_to='proyecto/', verbose_name='video')),
                ('entidad', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='aplicacion.Entidad')),
            ],
            options={
                'verbose_name': 'Proyecto',
                'verbose_name_plural': 'Proyectos',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Proyecto_del_año',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=40, null=True)),
                ('año', models.DateTimeField(verbose_name='fecha')),
                ('descripcion', models.CharField(max_length=300, null=True)),
                ('proyecto_del_año', models.BooleanField(default=True, verbose_name='proyecto_del_año')),
            ],
            options={
                'verbose_name': 'Proyecto_del_año',
                'verbose_name_plural': 'Proyectos_del_año',
                'ordering': ['año'],
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('videofile', models.FileField(null=True, upload_to='videos/', verbose_name='')),
            ],
            options={
                'verbose_name': 'Video',
                'verbose_name_plural': 'Videos',
            },
        ),
        migrations.CreateModel(
            name='Recurso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreRecurso', models.CharField(max_length=40)),
                ('archivo', models.FileField(null=True, upload_to='transferencias/')),
                ('link', models.URLField(blank=True, null=True)),
                ('imagen', models.ImageField(default='descarga.jpg', upload_to='recursos/')),
                ('status', models.BooleanField(default=True, verbose_name='status')),
                ('proyecto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='aplicacion.Proyecto')),
            ],
            options={
                'verbose_name': 'Recurso',
                'verbose_name_plural': 'Recursos',
            },
        ),
        migrations.AddField(
            model_name='proyecto',
            name='proyecto',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='aplicacion.Proyecto_del_año'),
        ),
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(blank=True, null=True)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('link', models.URLField(blank=True, max_length=500)),
                ('titulo', models.CharField(blank=True, max_length=100, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=300, null=True)),
                ('imagen', models.FileField(default='noticia.jpg', upload_to='noticia/')),
                ('body', models.TextField(blank=True, null=True)),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Noticia',
                'verbose_name_plural': 'Noticias',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Imagen_Proyecto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tituloProyecto', models.CharField(blank=True, max_length=400, null=True)),
                ('images', models.FileField(upload_to='images/')),
                ('imagenes', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='aplicacion.Proyecto')),
            ],
            options={
                'verbose_name': 'Imagen_Proyecto',
                'verbose_name_plural': 'Imagenes_Proyectos',
            },
        ),
        migrations.CreateModel(
            name='Imagen_Nosotros',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=400, null=True)),
                ('images', models.FileField(upload_to='images/')),
                ('imagenes', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='aplicacion.Nosotros')),
            ],
            options={
                'verbose_name': 'Imagen_Nosotros',
                'verbose_name_plural': 'Imagenes_Nosotros',
            },
        ),
        migrations.CreateModel(
            name='HistoricalProyecto',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('order', models.IntegerField(blank=True, null=True)),
                ('nombreProyecto', models.CharField(max_length=40, null=True)),
                ('año', models.DateTimeField(verbose_name='fecha')),
                ('descripcion', models.CharField(max_length=300, null=True)),
                ('imagenes', models.TextField(max_length=100)),
                ('video', models.TextField(max_length=100, null=True, verbose_name='video')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('entidad', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='aplicacion.Entidad')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('proyecto', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='aplicacion.Proyecto_del_año')),
            ],
            options={
                'verbose_name': 'historical Proyecto',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
